create  FUNCTION [dbo].Fn_DIAS_UTEIS_MES (@DATAINICIAL DATETIME, @DATAFINAL DATETIME,  @CODCALEND VARCHAR(MAX))

RETURNS INT

AS
BEGIN

-- CRIA VARIAVEIS

DECLARE @FERIADOS INT, @RETORNO INT, @DIASAUX INT, @DATAAUX DATETIME

SET @DATAINICIAL = @DATAINICIAL - 1 

-- SETA PRIMEIRO DIA DA SEMANA EM DOMINGO

--SET DATEFIRST 7

-- MONTA CURSOR

DECLARE CURSORFERIADO CURSOR FOR

SELECT COUNT(*) 'TOTAL' FROM GFERIADO

WHERE DIAFERIADO BETWEEN @DATAINICIAL  + 1   AND @DATAFINAL

AND DATEPART(DW, DIAFERIADO) NOT IN (1, 7) AND CODCALENDARIO = @CODCALEND

-- ABRE CURSOR

OPEN CURSORFERIADO

-- PEGA PRIMEIRO

FETCH NEXT FROM CURSORFERIADO INTO @FERIADOS

-- SETA DIAS ÚTEIS COMO 0

SET @RETORNO = DATEDIFF(DAY, @DATAINICIAL, @DATAFINAL)

-- SETA DATA AUXILIAR PARA CÁLCULOS

SET @DATAAUX = @DATAFINAL

-- CONTABILIZA DIAS ÚTEIS

WHILE @DATAINICIAL <= @DATAAUX

BEGIN

-- SE FOR FINAL DE SEMANA, DESCONSIDERA DO TOTAL

IF DATEPART(DW, @DATAAUX) IN (1, 7)

BEGIN

SET @RETORNO = @RETORNO - 1

END

-- SUBTRAI UM DA DATA AUXILIAR

SET @DATAAUX = @DATAAUX - 1

END

-- CORRIGE CASO DATA INICIAL SEJA UM FDS

IF DATEPART(DW, @DATAINICIAL) IN (1, 7)

BEGIN

SET @RETORNO = @RETORNO + 1

END

-- FECHA CURSOR

CLOSE CURSORFERIADO

DEALLOCATE CURSORFERIADO

-- DESCONSIDERA OS FERIADOS

SET @RETORNO = @RETORNO - @FERIADOS

RETURN(@RETORNO)
--SELECT (@RETORNO)


END

/*ALTER   FUNCTION Fn_DIAS_UTEIS_MES ( @Data_Inicial DateTime, @Data_Final DateTime)--,  @CODCALEND VARCHAR(MAX))
RETURNS INT

BEGIN 

declare @Dias as int	
declare @DiaSemana as int
declare @Data_Inicial_ori	DateTime = @Data_Inicial
declare @Data_Final_ori		DateTime = @Data_Final



set @Dias = 0
set @DiaSemana = 0

while @Data_inicial <= @data_final
	begin
		set @DiaSemana = DATEPART(weekday, @Data_inicial)
		if @DiaSemana <> 1 and @DiaSemana <> 7
			begin
				set @Dias = @Dias + 1	
			end

			set @Data_inicial = DateAdd(d, 1, @Data_inicial)

		
			set @Dias = @Dias  - (
			select isnull(count(*),0) from GFERIADO 
			where   CODCALENDARIO = '0000041'--@CODCALEND
				and diaferiado between @Data_inicial and @data_final
				)
		
		
	end RETURN 
 @Dias


end 	
*/


/*ALTER  FUNCTION [dbo].[Fn_DIAS_UTEIS_MES] (@DATAINICIAL DATETIME, @DATAFINAL DATETIME, @CODCALEND VARCHAR(MAX))

RETURNS INT

AS
BEGIN

-- CRIA VARIAVEIS

DECLARE @FERIADOS INT, @RETORNO INT, @DIASAUX INT, @DATAAUX DATETIME

SET @DATAINICIAL = @DATAINICIAL 

SET @DATAFINAL  = convert(varchar(10),@DATAFINAL,102) + ' 23:59:59'


-- SETA PRIMEIRO DIA DA SEMANA EM DOMINGO

--SET DATEFIRST 7

-- MONTA CURSOR

DECLARE CURSORFERIADO CURSOR FOR

SELECT COUNT(*) 'TOTAL' FROM GFERIADO

WHERE DIAFERIADO BETWEEN @DATAINICIAL  + 1   AND @DATAFINAL

AND DATEPART(DW, DIAFERIADO) NOT IN (1, 7) AND CODCALENDARIO = @CODCALEND

-- ABRE CURSOR

OPEN CURSORFERIADO

-- PEGA PRIMEIRO

FETCH NEXT FROM CURSORFERIADO INTO @FERIADOS

-- SETA DIAS ÚTEIS COMO 0

SET @RETORNO = DATEDIFF(DAY, @DATAINICIAL, @DATAFINAL)

-- SETA DATA AUXILIAR PARA CÁLCULOS

SET @DATAAUX = @DATAFINAL

-- CONTABILIZA DIAS ÚTEIS

WHILE @DATAINICIAL <= @DATAAUX

BEGIN

-- SE FOR FINAL DE SEMANA, DESCONSIDERA DO TOTAL

IF DATEPART(DW, @DATAAUX) IN (1, 7)

BEGIN

SET @RETORNO = @RETORNO - 1

END

-- SUBTRAI UM DA DATA AUXILIAR

SET @DATAAUX = @DATAAUX - 1

END

-- CORRIGE CASO DATA INICIAL SEJA UM FDS

IF DATEPART(DW, @DATAINICIAL) IN (1, 7)

BEGIN

SET @RETORNO = @RETORNO + 1

END

-- FECHA CURSOR

CLOSE CURSORFERIADO

DEALLOCATE CURSORFERIADO

-- DESCONSIDERA OS FERIADOS

SET @RETORNO = @RETORNO - @FERIADOS

RETURN(@RETORNO)
--SELECT (@RETORNO)


END*/